#!/usr/bin/env bash
# RTAK Inlet Setup — Reticulum over Internet
#
# Adds a TCPServerInterface to Reticulum so remote nodes can connect
# over the internet. Optionally wraps the connection in TLS via stunnel
# (stealth mode) so traffic looks identical to HTTPS on port 443.
#
# Usage:
#   sudo bash setup_inlet.sh              # basic TCP on port 4242
#   sudo bash setup_inlet.sh --port 9000 # custom port, basic
#   sudo bash setup_inlet.sh --stealth   # TLS on port 443
#   sudo bash setup_inlet.sh --stealth --port 8443  # TLS on custom port
#
# Prerequisites: setup_pi.sh must have run first.
# Certs are expected at /opt/rtak/certs/ (generated by setup_pi.sh).

set -euo pipefail

RNS_CONFIG="/etc/reticulum/config"
CERTS_DIR="/opt/rtak/certs"
STEALTH=false
PORT=4242

# ---------------------------------------------------------------------------
# Parse arguments
# ---------------------------------------------------------------------------
while [[ $# -gt 0 ]]; do
    case "$1" in
        --stealth)
            STEALTH=true
            PORT=443
            shift
            ;;
        --port)
            PORT="$2"
            shift 2
            ;;
        *)
            echo "Unknown argument: $1"
            echo "Usage: $0 [--stealth] [--port <port>]"
            exit 1
            ;;
    esac
done

echo "=== RTAK Inlet Setup ==="
echo "Mode:  $( $STEALTH && echo 'Stealth (TLS on port '$PORT')' || echo 'Basic (TCP on port '$PORT')' )"
echo ""

# ---------------------------------------------------------------------------
# 1. Append TCPServerInterface to Reticulum config
# ---------------------------------------------------------------------------
if $STEALTH; then
    # In stealth mode, Reticulum listens on localhost only.
    # stunnel handles the external TLS on $PORT and forwards to 127.0.0.1:4242.
    RTAN_LISTEN_IP="127.0.0.1"
    RTAN_LISTEN_PORT=4242
else
    RTAN_LISTEN_IP="0.0.0.0"
    RTAN_LISTEN_PORT="$PORT"
fi

if grep -q "\[interface:tcp_inlet\]" "$RNS_CONFIG"; then
    echo "[1/4] TCP inlet interface already present in $RNS_CONFIG — skipping"
else
    echo "[1/4] Adding TCP inlet interface to $RNS_CONFIG..."
    cat >> "$RNS_CONFIG" <<RETCFG

# RTAK Inlet — remote Reticulum nodes connect here over internet
[interface:tcp_inlet]
  type            = TCPServerInterface
  interface_enabled = True
  listen_ip       = $RTAN_LISTEN_IP
  listen_port     = $RTAN_LISTEN_PORT
RETCFG
    echo "  TCP inlet configured: $RTAN_LISTEN_IP:$RTAN_LISTEN_PORT"
fi

# ---------------------------------------------------------------------------
# 2. stunnel TLS wrapper (stealth mode only)
# ---------------------------------------------------------------------------
if $STEALTH; then
    echo "[2/4] Installing stunnel TLS wrapper..."
    apt-get install -y --no-install-recommends stunnel4

    # stunnel needs a combined PEM: key + cert
    STUNNEL_PEM="/opt/rtak/certs/stunnel.pem"
    cat "$CERTS_DIR/server.key" "$CERTS_DIR/server.crt" > "$STUNNEL_PEM"
    chmod 600 "$STUNNEL_PEM"

    cat > /etc/stunnel/rtak-inlet.conf <<STUNNELCFG
; RTAK Inlet — TLS wrapper for Reticulum TCP interface
; External: port $PORT (looks like HTTPS to any network observer)
; Internal: forwards to Reticulum's TCP listener on 127.0.0.1:4242

; Run as a daemon
foreground = no
pid        = /run/stunnel4/rtak-inlet.pid

[rtak-inlet]
accept  = 0.0.0.0:$PORT
connect = 127.0.0.1:4242
cert    = $STUNNEL_PEM
; Remote nodes can optionally validate this cert using the RTAK CA:
;   CAfile  = /opt/rtak/certs/ca.crt
;   verify  = 2
STUNNELCFG

    # Enable stunnel4 and start it
    sed -i 's/^ENABLED=0/ENABLED=1/' /etc/default/stunnel4 2>/dev/null || true
    systemctl enable stunnel4
    systemctl restart stunnel4
    echo "  stunnel TLS wrapper active on 0.0.0.0:$PORT → 127.0.0.1:4242"
    echo "  Traffic on port $PORT looks identical to HTTPS to any network observer"
else
    echo "[2/4] Basic mode — no TLS wrapper (skipping stunnel)"
fi

# ---------------------------------------------------------------------------
# 3. Firewall
# ---------------------------------------------------------------------------
echo "[3/4] Opening port $PORT/tcp in UFW..."
ufw allow "$PORT/tcp" comment "RTAK Inlet (Reticulum over internet)"
echo "  Port $PORT/tcp open"

# ---------------------------------------------------------------------------
# 4. Restart rnsd / Reticulum
# ---------------------------------------------------------------------------
echo "[4/4] Restarting Reticulum daemon to activate inlet..."
if systemctl is-active --quiet rnsd 2>/dev/null; then
    systemctl restart rnsd
    echo "  rnsd restarted"
elif systemctl is-active --quiet reticulum 2>/dev/null; then
    systemctl restart reticulum
    echo "  reticulum service restarted"
else
    echo "  Note: Reticulum service not found — restart rtak-bridge manually to pick up new interface"
fi

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
PUBLIC_IP=$(curl -s --max-time 5 https://api.ipify.org 2>/dev/null || echo "<your-public-ip>")

echo ""
echo "=== Inlet setup complete ==="
echo ""
if $STEALTH; then
    echo "Stealth mode: TLS on port $PORT (stunnel → Reticulum TCP on 4242)"
    echo "Traffic appears as HTTPS to DPI and network observers."
    echo ""
    echo "Remote node Reticulum config:"
    echo "---"
    echo "[interface:rtak_inlet]"
    echo "  type            = TCPClientInterface"
    echo "  interface_enabled = True"
    echo "  target_host     = $PUBLIC_IP"
    echo "  target_port     = $PORT"
    echo "---"
else
    echo "Basic mode: Reticulum TCP on port $PORT"
    echo ""
    echo "Remote node Reticulum config:"
    echo "---"
    echo "[interface:rtak_inlet]"
    echo "  type            = TCPClientInterface"
    echo "  interface_enabled = True"
    echo "  target_host     = $PUBLIC_IP"
    echo "  target_port     = $PORT"
    echo "---"
fi
echo ""
echo "Add the block above to /etc/reticulum/config (or ~/.reticulum/config)"
echo "on each remote node, then restart Reticulum on that node."
echo ""
echo "If your public IP changes, use a DDNS hostname instead:"
echo "  - DuckDNS: https://duckdns.org (free)"
echo "  - Afraid.org: https://freedns.afraid.org (free)"
echo ""
echo "Router port forward needed: external $PORT → $(hostname -I | awk '{print $1}'):$PORT"
