#!/usr/bin/env bash
# RTAK Node — Raspberry Pi Setup Script
# Tested on: Raspberry Pi OS Lite (64-bit), Bookworm
#
# What this does:
#   1. Updates system packages
#   2. Installs Python deps: rns, lxmf, pytak, FreeTAKServer
#   3. Deploys the RTAK bridge to /opt/rtak
#   4. Writes a Reticulum config for dual RNodes (915 + 433 MHz) + WiFi
#   5. Installs systemd services for FreeTAKServer and the bridge
#   6. Enables both services to start at boot
#
# Usage:
#   sudo bash setup_pi.sh
#
# After running:
#   1. Plug in both T-Beam RNodes via USB
#   2. Verify port assignments: ls /dev/ttyUSB*
#   3. Edit /etc/reticulum/config if port names differ from defaults
#   4. sudo systemctl start freetakserver rtak-bridge
#   5. Note the bridge hash printed in: journalctl -u rtak-bridge -f

set -euo pipefail

RTAK_USER="rtak"
RTAK_HOME="/opt/rtak"
RNS_CONFIG="/etc/reticulum"

# Ports — adjust if your system assigns them differently
# Run: ls /dev/ttyUSB* after plugging in both T-Beams
PORT_915="/dev/ttyUSB0"   # T-Beam Supreme (915 MHz)
PORT_433="/dev/ttyUSB1"   # T-Beam v1.1 (433 MHz)

# LoRa RF settings — US 915 MHz ISM band defaults
# Adjust for your regulatory region and link budget needs
FREQ_915=915000000
FREQ_433=433000000
BANDWIDTH=125000          # 125 kHz — balanced range vs speed
TXPOWER=17                # dBm — 17 dBm (~50 mW), legal everywhere
SF=8                      # Spreading factor 8 — good balance
CR=5                      # Coding rate 4/5

echo "=== RTAK Node Setup ==="
echo "Target: $RTAK_HOME"
echo "RNode 915: $PORT_915"
echo "RNode 433: $PORT_433"
echo ""

# ---------------------------------------------------------------------------
# 1. System packages
# ---------------------------------------------------------------------------
echo "[1/6] Updating system packages..."
apt-get update -qq
apt-get install -y --no-install-recommends \
    python3 python3-pip python3-venv \
    git usbutils

# ---------------------------------------------------------------------------
# 2. Flash RNode firmware (requires boards to be plugged in)
# ---------------------------------------------------------------------------
echo "[2/6] Installing rnodeconf and checking RNode firmware..."
pip3 install --quiet rnodeconf

echo "  Flashing 915 MHz RNode on $PORT_915..."
rnodeconf --autoinstall --freq $FREQ_915 --bw $BANDWIDTH --txp $TXPOWER \
    --sf $SF --cr $CR "$PORT_915" || \
    echo "  WARNING: Could not flash $PORT_915 — plug in T-Beam Supreme and rerun, or flash manually."

echo "  Flashing 433 MHz RNode on $PORT_433..."
rnodeconf --autoinstall --freq $FREQ_433 --bw $BANDWIDTH --txp $TXPOWER \
    --sf $SF --cr $CR "$PORT_433" || \
    echo "  WARNING: Could not flash $PORT_433 — plug in T-Beam v1.1 and rerun, or flash manually."

# ---------------------------------------------------------------------------
# 3. Create RTAK system user and deploy files
# ---------------------------------------------------------------------------
echo "[3/6] Creating rtak user and deploying files..."
id "$RTAK_USER" &>/dev/null || useradd --system --shell /usr/sbin/nologin \
    --home-dir "$RTAK_HOME" --create-home "$RTAK_USER"

# Add rtak user to dialout so it can access USB serial ports
usermod -aG dialout "$RTAK_USER"

# Copy bridge files
mkdir -p "$RTAK_HOME"
cp prototype.py "$RTAK_HOME/"
cp requirements.txt "$RTAK_HOME/"
cp rtak_peers.txt "$RTAK_HOME/" 2>/dev/null || touch "$RTAK_HOME/rtak_peers.txt"

# Create virtualenv and install Python deps
python3 -m venv "$RTAK_HOME/venv"
"$RTAK_HOME/venv/bin/pip" install --quiet -r "$RTAK_HOME/requirements.txt"

chown -R "$RTAK_USER:$RTAK_USER" "$RTAK_HOME"

# ---------------------------------------------------------------------------
# 4. Reticulum config
# ---------------------------------------------------------------------------
echo "[4/6] Writing Reticulum config..."
mkdir -p "$RNS_CONFIG"

cat > "$RNS_CONFIG/config" <<RETCONFIG
# Reticulum config — RTAK Node
# Generated by setup_pi.sh

[reticulum]
  enable_transport = True
  share_instance   = Yes
  shared_instance_port = 37428
  instance_control_port = 37429

# 915 MHz LoRa (T-Beam Supreme, SX1262)
[interface:lora_915]
  type             = RNodeInterface
  interface_enabled = True
  port             = $PORT_915
  frequency        = $FREQ_915
  bandwidth        = $BANDWIDTH
  txpower          = $TXPOWER
  spreadingfactor  = $SF
  codingrate       = $CR

# 433 MHz LoRa (T-Beam v1.1, SX1278)
[interface:lora_433]
  type             = RNodeInterface
  interface_enabled = True
  port             = $PORT_433
  frequency        = $FREQ_433
  bandwidth        = $BANDWIDTH
  txpower          = $TXPOWER
  spreadingfactor  = $SF
  codingrate       = $CR

# Local WiFi / Ethernet (auto-discovers other Reticulum nodes on LAN)
[interface:local_auto]
  type             = AutoInterface
  interface_enabled = True

# Uncomment to add an outbound TCP tunnel to a known remote node:
# [interface:tcp_relay]
#   type            = TCPClientInterface
#   interface_enabled = True
#   target_host     = your.relay.host
#   target_port     = 4242
RETCONFIG

echo "  Reticulum config written to $RNS_CONFIG/config"

# ---------------------------------------------------------------------------
# 5. FreeTAKServer
# ---------------------------------------------------------------------------
echo "[5/6] Installing FreeTAKServer..."
pip3 install --quiet FreeTAKServer

# Minimal FTS config — listens on all interfaces, CoT on TCP 8087
FTS_CONFIG="/etc/freetakserver"
mkdir -p "$FTS_CONFIG"
cat > "$FTS_CONFIG/FreeTAKServerConfig.py" <<FTSCONFIG
# FreeTAKServer minimal config for RTAK node
IP = '0.0.0.0'
CoTServicePort = 8087
SSLCoTServicePort = 8089
DataPackageServiceDefaultPort = 8080
UserConnectionString = 'sqlite:////opt/rtak/fts_data.db'
MainLoopDelay = 1
FTSCONFIG

# FTS systemd unit
cat > /etc/systemd/system/freetakserver.service <<FTSSVC
[Unit]
Description=FreeTAKServer
After=network.target
StartLimitIntervalSec=60
StartLimitBurst=5

[Service]
Type=simple
User=$RTAK_USER
WorkingDirectory=$RTAK_HOME
ExecStart=/usr/bin/python3 -m FreeTAKServer.controllers.services.FTS
Restart=on-failure
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
FTSSVC

# ---------------------------------------------------------------------------
# 6. RTAK bridge systemd unit
# ---------------------------------------------------------------------------
echo "[6/6] Installing RTAK bridge systemd service..."
cat > /etc/systemd/system/rtak-bridge.service <<BRIDGESVC
[Unit]
Description=RTAK Bridge — CoT over Reticulum
After=network.target freetakserver.service
Requires=freetakserver.service
StartLimitIntervalSec=60
StartLimitBurst=5

[Service]
Type=simple
User=$RTAK_USER
WorkingDirectory=$RTAK_HOME
ExecStart=$RTAK_HOME/venv/bin/python $RTAK_HOME/prototype.py
Restart=on-failure
RestartSec=15
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
BRIDGESVC

systemctl daemon-reload
systemctl enable freetakserver rtak-bridge

echo ""
echo "=== Setup complete ==="
echo ""
echo "Next steps:"
echo "  1. Verify RNode ports:  ls /dev/ttyUSB*"
echo "     If they differ from $PORT_915 / $PORT_433, edit $RNS_CONFIG/config"
echo ""
echo "  2. Start services:"
echo "     sudo systemctl start freetakserver rtak-bridge"
echo ""
echo "  3. Check bridge is running and note your node hash:"
echo "     sudo journalctl -u rtak-bridge -f"
echo ""
echo "  4. Share your hash with other node operators."
echo "     Add their hashes to $RTAK_HOME/rtak_peers.txt (one per line)"
echo ""
echo "  5. Point ATAK clients at this Pi's IP on port 8087 (TCP CoT)"
echo ""
echo "FTS data:    $RTAK_HOME/fts_data.db"
echo "RNS config:  $RNS_CONFIG/config"
echo "Peer list:   $RTAK_HOME/rtak_peers.txt"
