#!/usr/bin/env bash
# RTAK RelayNode — Raspberry Pi Zero 2W Setup Script
#
# What this does:
#   1. Installs Reticulum Network Stack (rns)
#   2. Writes /etc/reticulum/config with dual RNode (915 + 433 MHz) + WiFi auto-discovery
#   3. Enables transport mode — the single setting that makes this node a relay
#   4. Installs rnsd as a systemd service (auto-starts on boot)
#   5. Hardens firewall: SSH only (no FTS ports — this node has no TAK stack)
#
# Usage:
#   sudo bash setup_relay.sh
#
# Prerequisites:
#   - Both T-Beams flashed with RNode firmware (rnodeconf --autoinstall)
#   - Both T-Beams connected via OTG hub
#   - Correct port assignments in PORT_915 / PORT_433 below

set -euo pipefail

# ─── RF port assignments ──────────────────────────────────────────────────────
# Verify with: ls /dev/ttyUSB*  (unplug one T-Beam at a time to confirm which is which)
PORT_915="/dev/ttyUSB0"   # T-Beam Supreme (915 MHz, SX1262)
PORT_433="/dev/ttyUSB1"   # T-Beam v1.1   (433 MHz, SX1278)

# ─── LoRa RF settings ─────────────────────────────────────────────────────────
# MUST match OmniNode /etc/reticulum/config for cross-node communication.
# Any mismatch (frequency, bandwidth, SF, CR) = nodes cannot hear each other.
FREQ_915=915000000
FREQ_433=433000000
BANDWIDTH=125000
TXPOWER=17
SF=8
CR=5

# ─── Paths ────────────────────────────────────────────────────────────────────
RNS_CONFIG_DIR="/etc/reticulum"
RNS_CONFIG="$RNS_CONFIG_DIR/config"

# ─────────────────────────────────────────────────────────────────────────────

echo "=== RTAK RelayNode Setup ==="
echo "  RNode 915 MHz : $PORT_915"
echo "  RNode 433 MHz : $PORT_433"
echo ""

# ── 1. System packages ────────────────────────────────────────────────────────
echo "[1/4] Updating packages..."
apt-get update -qq
apt-get install -y --no-install-recommends \
    python3 python3-pip \
    usbutils ufw

# ── 2. Reticulum ──────────────────────────────────────────────────────────────
echo "[2/4] Installing Reticulum Network Stack..."
pip3 install --quiet rns

# ── 3. Reticulum config ───────────────────────────────────────────────────────
echo "[3/4] Writing Reticulum config (transport mode)..."
mkdir -p "$RNS_CONFIG_DIR"

cat > "$RNS_CONFIG" <<RETCONFIG
# Reticulum config — RTAK RelayNode
# Generated by setup_relay.sh
#
# enable_transport = True is what makes this a relay.
# Packets received on any interface are forwarded to all other interfaces.
# LXMF messages are also buffered in the propagation store and retransmitted
# when a destination node comes back in range.

[reticulum]
  enable_transport       = True
  share_instance         = Yes
  shared_instance_port   = 37428
  instance_control_port  = 37429

# 915 MHz LoRa — T-Beam Supreme (SX1262)
[interface:lora_915]
  type              = RNodeInterface
  interface_enabled = True
  port              = $PORT_915
  frequency         = $FREQ_915
  bandwidth         = $BANDWIDTH
  txpower           = $TXPOWER
  spreadingfactor   = $SF
  codingrate        = $CR

# 433 MHz LoRa — T-Beam v1.1 (SX1278)
[interface:lora_433]
  type              = RNodeInterface
  interface_enabled = True
  port              = $PORT_433
  frequency         = $FREQ_433
  bandwidth         = $BANDWIDTH
  txpower           = $TXPOWER
  spreadingfactor   = $SF
  codingrate        = $CR

# WiFi/LAN — auto-discovers other Reticulum nodes on local network
# Useful if the relay is mounted near a structure with WiFi access
[interface:local_auto]
  type              = AutoInterface
  interface_enabled = True
RETCONFIG

echo "  Written: $RNS_CONFIG"

# ── 4. systemd service + firewall ─────────────────────────────────────────────
echo "[4/4] Installing rnsd service and hardening firewall..."

cat > /etc/systemd/system/rnsd.service <<RNSSVC
[Unit]
Description=Reticulum Network Stack Daemon — RTAK RelayNode
After=network.target
StartLimitIntervalSec=60
StartLimitBurst=5

[Service]
Type=simple
ExecStart=/usr/local/bin/rnsd --config $RNS_CONFIG_DIR
Restart=on-failure
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
RNSSVC

systemctl daemon-reload
systemctl enable rnsd

# Relay nodes only need SSH — no FTS ports
ufw --force reset >/dev/null
ufw default deny incoming
ufw default allow outgoing
ufw allow ssh
ufw --force enable

echo "  UFW enabled. Open: 22/tcp (SSH) only."

# ─────────────────────────────────────────────────────────────────────────────
echo ""
echo "=== Setup complete ==="
echo ""
echo "Next steps:"
echo ""
echo "  1. Verify RNode port assignments:"
echo "     ls /dev/ttyUSB*"
echo "     If they differ from $PORT_915 / $PORT_433, edit $RNS_CONFIG"
echo ""
echo "  2. Start the relay:"
echo "     sudo systemctl start rnsd"
echo ""
echo "  3. Check it is running and routing:"
echo "     sudo journalctl -u rnsd -f"
echo "     rnstatus                     # shows active interfaces + link status"
echo ""
echo "  4. Verify relay routing from an OmniNode:"
echo "     rnprobe <omninode-destination-hash>"
echo "     Route path should show this relay's hash as an intermediate hop."
echo ""
echo "  NOTE: RF settings in $RNS_CONFIG MUST match your OmniNode config."
echo "  Frequency, bandwidth, or SF mismatch = no link between nodes."
